{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "quickstart-java-service.serviceAccountName" . }}
  labels:
    {{- include "quickstart-java-service.labels" . | nindent 4 }}
  {{- $konveyor := include "quickstart-java-service.konveyorAnnotations" . | fromYaml }}
  {{- $merged := merge (default dict .Values.serviceAccount.annotations) $konveyor }}
  {{- with $merged }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
