apiVersion: v1
kind: Service
metadata:
  name: {{ include "quickstart-java-service.fullname" . }}
  labels:
    {{- include "quickstart-java-service.labels" . | nindent 4 }}
  {{- with (include "quickstart-java-service.konveyorAnnotations" . | fromYaml) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "quickstart-java-service.selectorLabels" . | nindent 4 }}
